from __future__ import annotations

import asyncio
from typing import Callable, List, Optional

from ragcheck.core import EvalResult, evaluate


async def aevaluate(
    question: str,
    answer: str,
    contexts: List[str],
    llm_fn: Callable[[str], str],
    **evaluate_kwargs,
) -> EvalResult:
    """Async version of evaluate(). Wraps the sync llm_fn with asyncio.to_thread().

    Accepts the same keyword arguments as evaluate() (model, pricing,
    include_context_recall, extra_metrics).

    Args:
        question: The user's original question.
        answer: The answer generated by the RAG system.
        contexts: The list of retrieved context chunks.
        llm_fn: Any sync callable that takes a prompt string and returns a string.
        **evaluate_kwargs: Forwarded to evaluate().

    Returns:
        EvalResult — same as evaluate().
    """
    return await asyncio.to_thread(
        evaluate, question, answer, contexts, llm_fn, **evaluate_kwargs
    )


async def aevaluate_batch(
    items: List[dict],
    llm_fn: Callable[[str], str],
    *,
    concurrency: int = 5,
    **evaluate_kwargs,
) -> List[EvalResult]:
    """Async batch evaluation with semaphore-based concurrency control.

    Args:
        items: List of dicts with keys "question", "answer", "contexts".
        llm_fn: Any sync callable that takes a prompt string and returns a string.
        concurrency: Maximum number of concurrent evaluate() calls. Default 5.
        **evaluate_kwargs: Forwarded to aevaluate().

    Returns:
        List of EvalResult in the same order as items.
    """
    if not items:
        return []

    sem = asyncio.Semaphore(concurrency)

    async def bounded(item: dict) -> EvalResult:
        async with sem:
            return await aevaluate(
                question=item["question"],
                answer=item["answer"],
                contexts=item["contexts"],
                llm_fn=llm_fn,
                **evaluate_kwargs,
            )

    return list(await asyncio.gather(*[bounded(item) for item in items]))
