from __future__ import annotations

import json
import re
from dataclasses import dataclass
from typing import Callable, List


@dataclass
class EvalResult:
    faithfulness: float
    answer_relevance: float
    context_precision: float
    reasoning: dict[str, str]


def _format_contexts(contexts: List[str]) -> str:
    if not contexts:
        return "(no context provided)"
    return "\n".join(f"[{i+1}] {ctx}" for i, ctx in enumerate(contexts))


def _parse_llm_json(response: str) -> tuple[float, str]:
    """Parse LLM response into (score, reasoning). Falls back gracefully on bad JSON."""
    def extract(obj: dict) -> tuple[float, str]:
        score = float(obj.get("score", 0.0))
        score = max(0.0, min(1.0, score))
        reasoning = str(obj.get("reasoning", ""))
        return score, reasoning

    try:
        parsed = json.loads(response.strip())
        if isinstance(parsed, dict):
            return extract(parsed)
    except (json.JSONDecodeError, ValueError, TypeError):
        pass

    match = re.search(r'\{[^{}]*\}', response, re.DOTALL)
    if match:
        try:
            return extract(json.loads(match.group()))
        except (json.JSONDecodeError, ValueError, TypeError):
            pass

    return 0.0, f"JSON parse error: {response[:200]}"


def _faithfulness_prompt(question: str, answer: str, contexts: List[str]) -> str:
    return f"""You are evaluating whether an answer is faithful to the provided context.

Question: {question}

Answer: {answer}

Context:
{_format_contexts(contexts)}

Score 1.0 if every claim in the answer is directly supported by the context.
Score 0.0 if the answer contains claims not found in the context.
Score between 0 and 1 proportionally for partial support.

Respond ONLY with valid JSON: {{"score": <float 0-1>, "reasoning": "<one sentence>"}}"""


def _answer_relevance_prompt(question: str, answer: str) -> str:
    return f"""You are evaluating whether an answer is relevant to the question asked.

Question: {question}

Answer: {answer}

Score 1.0 if the answer directly and completely addresses the question.
Score 0.0 if the answer is completely off-topic or refuses to answer.
Score between 0 and 1 for partial relevance.

Respond ONLY with valid JSON: {{"score": <float 0-1>, "reasoning": "<one sentence>"}}"""


def _context_precision_prompt(question: str, contexts: List[str]) -> str:
    return f"""You are evaluating whether the retrieved context is relevant and useful for answering the question.

Question: {question}

Context:
{_format_contexts(contexts)}

Score 1.0 if all context chunks are highly relevant to answering the question.
Score 0.0 if none of the context chunks are relevant.
Score between 0 and 1 proportionally based on the fraction of relevant chunks.

Respond ONLY with valid JSON: {{"score": <float 0-1>, "reasoning": "<one sentence>"}}"""


def evaluate(
    question: str,
    answer: str,
    contexts: List[str],
    llm_fn: Callable[[str], str],
) -> EvalResult:
    """
    Evaluate a RAG response across three metrics.

    Args:
        question: The user's original question.
        answer: The answer generated by the RAG system.
        contexts: The list of retrieved context chunks.
        llm_fn: Any callable that takes a prompt string and returns a string.

    Returns:
        EvalResult with faithfulness, answer_relevance, context_precision scores (0-1)
        and per-metric reasoning strings.
    """
    faith_score, faith_reason = _parse_llm_json(
        llm_fn(_faithfulness_prompt(question, answer, contexts))
    )
    relevance_score, relevance_reason = _parse_llm_json(
        llm_fn(_answer_relevance_prompt(question, answer))
    )
    precision_score, precision_reason = _parse_llm_json(
        llm_fn(_context_precision_prompt(question, contexts))
    )

    return EvalResult(
        faithfulness=faith_score,
        answer_relevance=relevance_score,
        context_precision=precision_score,
        reasoning={
            "faithfulness": faith_reason,
            "answer_relevance": relevance_reason,
            "context_precision": precision_reason,
        },
    )
